# Generated by Django 2.0 on 2018-09-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180911_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='article',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
