# Generated by Django 2.0 on 2018-10-15 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myaccount.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('uid', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('avatar', models.ImageField(default='avatar\\default.jpg', upload_to=myaccount.models.user_directory_path, verbose_name='头像')),
                ('sex', models.CharField(default='保密', max_length=20)),
                ('birth', models.DateTimeField(blank=True, null=True, verbose_name='birth date')),
                ('address', models.CharField(default='未知', max_length=200)),
                ('org', models.CharField(blank=True, max_length=128, verbose_name='Organization')),
                ('job', models.CharField(blank=True, max_length=128, verbose_name='Job')),
                ('join_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='join date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Mod date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
